### Get All restaurants
GET http://localhost:8081/restaurants
Content-Type: application/json

### Generate a new restaurant
POST http://localhost:8081/restaurants
Content-Type: application/json

{
  "name": "Test Restaurant",
  "location": "Test Location",
  "contactInfo": "test@restaurant.com"
}

### Get the list of restaurants
GET http://localhost:8081/restaurants
Content-Type: application/json

### Get restaurants filtered by name
GET http://localhost:8081/restaurants?name=Test%20Restaurant
Content-Type: application/json

### Update the restaurant
PUT http://localhost:8081/restaurants/4
Content-Type: application/json

{
  "name": "Updated Test Restaurant",
  "location": "Updated Test Location",
  "contactInfo": "updated@testrestaurant.com"
}

### Get the restaurant
GET http://localhost:8081/restaurants/5
Content-Type: application/json

### Delete the restaurant
### DELETE http://localhost:8081/restaurants/4
### Content-Type: application/json

### Generate a new restaurant (again)
POST http://localhost:8081/restaurants
Content-Type: application/json

{
  "name": "Another Test Restaurant",
  "location": "Another Test Location",
  "contactInfo": "another@testrestaurant.com"
}

### Get the menu of the restaurant
GET http://localhost:8082/restaurants/1/menu
Content-Type: application/json

### Create the menu of the restaurant
POST http://localhost:8082/restaurants/1/menu
Content-Type: application/json

### Get the menu of the restaurant (after creation)
GET http://localhost:8082/restaurants/4/menu
Content-Type: application/json

### Get the menu
GET http://localhost:8082/restaurants/4/menu/30
Content-Type: application/json

### Delete the menu
### DELETE http://localhost:8082/restaurants/4/menu/5
### Content-Type: application/json

### Create the menu for the restaurant (again)
POST http://localhost:8082/restaurants/4/menu
Content-Type: application/json

### Create a new menu item for the restaurant
POST http://localhost:8082/restaurants/4/menu/30/items
Content-Type: application/json

{
  "name": "New Menu Item",
  "description": "A new menu item description",
  "price": 10.5,
  "category": "Main Course",
  "availability": true,
  "dietaryInfo": "Vegan"
}

### Get the list of items in the restaurant’s menu
GET http://localhost:8082/restaurants/4/menu/30/items
Content-Type: application/json


### Delete a menu item for the restaurant
DELETE http://localhost:8082/restaurants/4/menu/6/items/7
Content-Type: application/json


### ORDERS

### Get All orders
GET http://localhost:8083/orders
Content-Type: application/json

### Generate a new order
POST http://localhost:8083/orders
Content-Type: application/json

{
  "status": "NEW",
  "restaurantId": 1,
  "tableId": 1,
  "dinerId": 1
}

### Update the order
PUT http://localhost:8083/orders/1
Content-Type: application/json

{
  "status": "IN_PROGRESS",
  "restaurantId": 1,
  "tableId": 1,
  "dinerId": 1
}

### Get the order
GET http://localhost:8083/orders/1
Content-Type: application/json

### Delete the order
#DELETE http://localhost:8083/orders/2
#Content-Type: application/json


### ORDER DETAILS

### Get All order details
GET http://localhost:8083/orders/1/orderDetails
Content-Type: application/json

### Generate a new order detail
POST http://localhost:8083/orders/1/orderDetails
Content-Type: application/json

{
  "orderId": 1,
  "menuItemId": 1,
  "quantity": 3
}

### Update the order detail
PUT http://localhost:8083/orders/1/orderDetails/1
Content-Type: application/json

{
  "orderId": 1,
  "menuItemId": 1,
  "quantity": 4
}

### Get the order detail
GET http://localhost:8083/orders/1/orderDetails/1
Content-Type: application/json

### Delete the order
#DELETE http://localhost:8083/orders/1/orderDetails/2
#Content-Type: application/json